services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=levelup
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
